title: List Hosts Communicated with Internal IP
id: RA2102
description: >
  List hosts communicated with an internal IP address
author: name/nickname/twitter
creation_date: YYYY/MM/DD
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.
