title: RA_0034_identification_find_all_victims_in_security_alerts
stage: identification
automation:
  - thehive
author: Name Surname
creation_date: DD.MM.YYYY
references: 
  - https://example.com
description: >
  Response Action for 
workflow: |
  Description of how to handle multiple Response Actions (if it is an aggregated Response Action) or workflow for single Response Action in markdown format.
  Here newlines will be saved.  



