title: "RA_1601_manage_remote_computer_management_system_policies"
id: "RA1601"
description: >
  Make sure you can manage Remote Computer Management system policies
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for single Response Action in markdown format.
  Here newlines will be saved.
