title: "RA_1208_access_dhcp_logs"
id: "RA1208"
description: >
  Make sure you have access to DHCP logs
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for single Response Action in markdown format.
  Here newlines will be saved.
