title: "RA_1209_access_network_security_monitoring_system_logs"
id: "RA1209"
description: >
  Make sure you have access to network security monitoring system logs
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for single Response Action in markdown format.
  Here newlines will be saved.
