title: RA_2201_list_users_opened_email_message
id: RA2201
description: >
  List users that have opened am email message
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
