title: RA_2202_list_hosts_communicated_with_IP
id: RA2202
description: >
  Response Action for 
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of how to handle multiple Response Actions (if it is an aggregated Response Action) or workflow for single Response Action in markdown format.
  Here newlines will be saved.  
