title: RA_2406_analyse_MS_Office_file
id: RA2406
description: >
  Response Action for 
author: name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
