title: RA_2203_list_email_receivers
id: RA2203
description: >
  List receivers of a specific email
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: identification
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
