title: RA_4301_remove_file_from_host
id: RA4301
description: >
  Remove a file from a host
author: your name/nickname/twitter
creation_date: DD.MM.YYYY
stage: eradication
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
