site_name: ATC RE&CT
docs_dir: ./generated_analytics/markdown_documents/

theme:
    name: 'rtd-dropdown'
    highlightjs: true
    hljs_style: github
    collapse_navigation: true

nav:
- Introduction:
    - RE&CT: README.md
- Response Actions:
    - Preparation:
        - "RA1101: Practice": ./Response_Actions/RA_1101_practice.md
        - "RA1102: Take trainings": ./Response_Actions/RA_1102_take_trainings.md
        - "RA1103: Raise personnel awareness": ./Response_Actions/RA_1103_raise_personnel_awareness.md
        - "RA1104: Make personnel report suspicious activity": ./Response_Actions/RA_1104_make_personnel_report_suspicious_activity.md
        - "RA1105: Set up relevant data collection": ./Response_Actions/RA_1105_set_up_relevant_data_collection.md
        - "RA1106: Set up a centralized long-term log storage": ./Response_Actions/RA_1106_set_up_a_centralized_long-term_log_storage.md
        - "RA1107: Develop communication map": ./Response_Actions/RA_1107_develop_communication_map.md
        - "RA1108: Make sure there are backups": ./Response_Actions/RA_1108_make_sure_there_are_backups.md
        - "RA1109: Get network architecture map": ./Response_Actions/RA_1109_get_network_architecture_map.md
        - "RA1110: Get access control matrix": ./Response_Actions/RA_1110_get_access_control_matrix.md
        - "RA1111: Develop assets knowledge base": ./Response_Actions/RA_1111_develop_assets_knowledge_base.md
        - "RA1112: Check analysis toolset": ./Response_Actions/RA_1112_check_analysis_toolset.md
        - "RA1113: Access vulnerability management system logs": ./Response_Actions/RA_1113_access_vulnerability_management_system_logs.md
        - "RA1201: Access external network flow logs": ./Response_Actions/RA_1201_access_external_network_flow_logs.md
        - "RA1202: Access internal network flow logs": ./Response_Actions/RA_1202_access_internal_network_flow_logs.md
        - "RA1203: Access internal HTTP logs": ./Response_Actions/RA_1203_access_internal_http_logs.md
        - "RA1204: Access external HTTP logs": ./Response_Actions/RA_1204_access_external_http_logs.md
        - "RA1205: Access internal DNS logs": ./Response_Actions/RA_1205_access_internal_dns_logs.md
        - "RA1206: Access external DNS logs": ./Response_Actions/RA_1206_access_external_dns_logs.md
        - "RA1207: Access VPN logs": ./Response_Actions/RA_1207_access_vpn_logs.md
        - "RA1208: Access DHCP logs": ./Response_Actions/RA_1208_access_dhcp_logs.md
        - "RA1209: Access internal packet capture data": ./Response_Actions/RA_1209_access_internal_packet_capture_data.md
        - "RA1210: Access external packet capture data": ./Response_Actions/RA_1210_access_external_packet_capture_data.md
        - "RA1211: Get ability to block external IP address": ./Response_Actions/RA_1211_get_ability_to_block_external_ip_address.md
        - "RA1212: Get ability to block internal IP address": ./Response_Actions/RA_1212_get_ability_to_block_internal_ip_address.md
        - "RA1213: Get ability to block external domain": ./Response_Actions/RA_1213_get_ability_to_block_external_domain.md
        - "RA1214: Get ability to block internal domain": ./Response_Actions/RA_1214_get_ability_to_block_internal_domain.md
        - "RA1215: Get ability to block external URL": ./Response_Actions/RA_1215_get_ability_to_block_external_url.md
        - "RA1216: Get ability to block internal URL": ./Response_Actions/RA_1216_get_ability_to_block_internal_url.md
        - "RA1217: Get ability to block port external communication": ./Response_Actions/RA_1217_get_ability_to_block_port_external_communication.md
        - "RA1218: Get ability to block port internal communication": ./Response_Actions/RA_1218_get_ability_to_block_port_internal_communication.md
        - "RA1219: Get ability to block user external communication": ./Response_Actions/RA_1219_get_ability_to_block_user_external_communication.md
        - "RA1220: Get ability to block user internal communication": ./Response_Actions/RA_1220_get_ability_to_block_user_internal_communication.md
        - "RA1301: Get ability to list users opened email": ./Response_Actions/RA_1301_get_ability_to_list_users_opened_email.md
        - "RA1302: Get ability to list users received email": ./Response_Actions/RA_1302_get_ability_to_list_users_received_email.md
        - "RA1303: Get ability to block email domain": ./Response_Actions/RA_1303_get_ability_to_block_email_domain.md
        - "RA1304: Get ability to block email sender": ./Response_Actions/RA_1304_get_ability_to_block_email_sender.md
        - "RA1305: Get ability to delete email": ./Response_Actions/RA_1305_get_ability_to_delete_email.md
        - "RA1401: Get ability to find file by format": ./Response_Actions/RA_1401_get_ability_to_find_file_by_format.md
        - "RA1402: Get ability to find file by hash": ./Response_Actions/RA_1402_get_ability_to_find_file_by_hash.md
        - "RA1403: Get ability to find file by path": ./Response_Actions/RA_1403_get_ability_to_find_file_by_path.md
        - "RA1404: Get ability to find file by content pattern": ./Response_Actions/RA_1404_get_ability_to_find_file_by_content_pattern.md
        - "RA1405: Get ability to find file by metadata": ./Response_Actions/RA_1405_get_ability_to_find_file_by_metadata.md
        - "RA1406: Get ability to find files with tampered timestamps": ./Response_Actions/RA_1406_get_ability_to_find_files_with_tampered_timestamps.md
        - "RA1407: Get ability to list files modified": ./Response_Actions/RA_1407_get_ability_to_list_files_modified.md
        - "RA1408: Get ability to list files deleted": ./Response_Actions/RA_1408_get_ability_to_list_files_deleted.md
        - "RA1409: Get ability to list files downloaded": ./Response_Actions/RA_1409_get_ability_to_list_files_downloaded.md
        - "RA1410: Get ability to download file from host": ./Response_Actions/RA_1410_get_ability_to_download_file_from_host.md
        - "RA1411: Get ability to quarantine file by format": ./Response_Actions/RA_1411_get_ability_to_quarantine_file_by_format.md
        - "RA1412: Get ability to quarantine file by hash": ./Response_Actions/RA_1412_get_ability_to_quarantine_file_by_hash.md
        - "RA1413: Get ability to quarantine file by path": ./Response_Actions/RA_1413_get_ability_to_quarantine_file_by_path.md
        - "RA1414: Get ability to quarantine file by content pattern": ./Response_Actions/RA_1414_get_ability_to_quarantine_file_by_content_pattern.md
        - "RA1415: Get ability to quarantine file by metadata": ./Response_Actions/RA_1415_get_ability_to_quarantine_file_by_metadata.md
        - "RA1416: Get ability to remove file from host": ./Response_Actions/RA_1416_get_ability_to_remove_file_from_host.md
        - "RA1601: Manage remote computer management system policies": ./Response_Actions/RA_1601_manage_remote_computer_management_system_policies.md
    - Identification:
        - "RA2101: Extract observables from email": ./Response_Actions/RA_2305_extract_observables_from_email.md
        - "RA2103: Put compromised accounts on monitoring": ./Response_Actions/RA_2103_put_compromised_accounts_on_monitoring.md
        - "RA2104: List victims of security alert": ./Response_Actions/RA_2101_list_victims_of_security_alert.md
        - "RA2104: Make sure email is a phishing": ./Response_Actions/RA_2304_make_sure_email_is_a_phishing.md
        - "RA2105: List host vulnerabilities": ./Response_Actions/RA_2102_list_host_vulnerabilities.md
        - "RA2201: List hosts communicated with internal domain": ./Response_Actions/RA_2201_list_hosts_communicated_with_internal_domain.md
        - "RA2202: List hosts communicated with internal IP": ./Response_Actions/RA_2202_list_hosts_communicated_with_internal_ip.md
        - "RA2203: List hosts communicated with internal URL": ./Response_Actions/RA_2203_list_hosts_communicated_with_internal_url.md
        - "RA2204: Analyse domain name": ./Response_Actions/RA_2204_analyse_domain_name.md
        - "RA2205: Analyse IP": ./Response_Actions/RA_2205_analyse_ip.md
        - "RA2206: Analyse URL": ./Response_Actions/RA_2206_analyse_uri.md
        - "RA2207: List hosts communicated by port": ./Response_Actions/RA_2207_list_hosts_communicated_by_port.md
        - "RA2208: List hosts connected to VPN": ./Response_Actions/RA_2208_list_hosts_connected_to_vpn.md
        - "RA2209: List host connected to intranet": ./Response_Actions/RA_2209_list_host_connected_to_intranet.md
        - "RA2210: Get data transferred by FTP": ./Response_Actions/RA_2210_get_data_transferred_by_ftp.md
        - "RA2211: Get data transferred by SMB": ./Response_Actions/RA_2211_get_data_transferred_by_smb.md
        - "RA2212: Get data transferred by HTTP": ./Response_Actions/RA_2212_get_data_transferred_by_http.md
        - "RA2213: List hosts communicated with external domain": ./Response_Actions/RA_2213_list_hosts_communicated_with_external_domain.md
        - "RA2214: List hosts communicated with external ip.": ./Response_Actions/RA_2214_list_hosts_communicated_with_external_ip.md
        - "RA2215: List hosts communicated with external URL": ./Response_Actions/RA_2215_list_hosts_communicated_with_external_url.md
        - "RA2301: List users opened email": ./Response_Actions/RA_2301_list_users_opened_email.md
        - "RA2302: Get original email": ./Response_Actions/RA_2302_get_original_email.md
        - "RA2303: List email receivers": ./Response_Actions/RA_2303_list_email_receivers.md
        - "RA2401: List files created": ./Response_Actions/RA_2401_list_files_created.md
        - "RA2402: Analyse Windows PE": ./Response_Actions/RA_2402_analyse_windows_pe.md
        - "RA2403: List processes executed": ./Response_Actions/RA_2403_list_processes_executed.md
        - "RA2404: Analyse filehash": ./Response_Actions/RA_2404_analyse_filehash.md
        - "RA2405: Analyse macos mach-o": ./Response_Actions/RA_2405_analyse_macos_macho.md
        - "RA2406: Analyse MS office file": ./Response_Actions/RA_2406_analyse_ms_office_file.md
        - "RA2407: Analyse PDF": ./Response_Actions/RA_2407_analyse_pdf.md
        - "RA2408: Analyse Unix ELF": ./Response_Actions/RA_2408_analyse_unix_elf.md
        - "RA2409: Find file by format": ./Response_Actions/RA_2409_find_file_by_format.md
        - "RA2410: Find file by hash": ./Response_Actions/RA_2410_find_file_by_hash.md
        - "RA2411: Find file by path": ./Response_Actions/RA_2411_find_file_by_path.md
        - "RA2412: Find file by content pattern": ./Response_Actions/RA_2412_find_file_by_content_pattern.md
        - "RA2413: Find file by metadata": ./Response_Actions/RA_2413_find_file_by_metadata.md
        - "RA2414: List files modified": ./Response_Actions/RA_2414_list_files_modified.md
        - "RA2415: List files deleted": ./Response_Actions/RA_2415_list_files_deleted.md
        - "RA2416: List files downloaded": ./Response_Actions/RA_2416_list_files_downloaded.md
        - "RA2417: List files with tampered timestamps": ./Response_Actions/RA_2417_list_files_with_tampered_timestamps.md
        - "RA2418: Download file from host": ./Response_Actions/RA_2418_download_file_from_host.md
        - "RA2501: List services executed": ./Response_Actions/RA_2501_list_services_executed.md
        - "RA2601: List registry keys modified": ./Response_Actions/RA_2601_list_registry_keys_modified.md
    - Containment:
        - "RA3201: Block external IP address": ./Response_Actions/RA_3201_block_external_ip_address.md
        - "RA3202: Block internal IP address": ./Response_Actions/RA_3202_block_internal_ip_address.md
        - "RA3203: Block external domain": ./Response_Actions/RA_3203_block_external_domain.md
        - "RA3204: Block internal domain": ./Response_Actions/RA_3204_block_internal_domain.md
        - "RA3205: Block external URL": ./Response_Actions/RA_3205_block_external_url.md
        - "RA3206: Block internal URL": ./Response_Actions/RA_3206_block_internal_url.md
        - "RA3207: Block port external communication": ./Response_Actions/RA_3207_block_port_external_communication.md
        - "RA3208: Block port internal communication": ./Response_Actions/RA_3208_block_port_internal_communication.md
        - "RA3209: Block user external communication": ./Response_Actions/RA_3209_block_user_external_communication.md
        - "RA3210: Block user internal communication": ./Response_Actions/RA_3210_block_user_internal_communication.md
        - "RA3301: Block domain on email": ./Response_Actions/RA_3301_block_domain_on_email.md
        - "RA3302: Block sender on email": ./Response_Actions/RA_3302_block_sender_on_email.md
        - "RA3401: Quarantine file by format": ./Response_Actions/RA_3401_quarantine_file_by_format.md
        - "RA3402: Quarantine file by hash": ./Response_Actions/RA_3402_quarantine_file_by_hash.md
        - "RA3403: Quarantine file by path": ./Response_Actions/RA_3403_quarantine_file_by_path.md
        - "RA3404: Quarantine file by content pattern": ./Response_Actions/RA_3404_quarantine_file_by_content_pattern.md
        - "RA3405: Quarantine file by metadata": ./Response_Actions/RA_3405_quarantine_file_by_metadata.md
    - Eradication:
        - "RA4101: Report phishing attack to external companies": ./Response_Actions/RA_4101_report_phishing_attack_to_external_companies.md
        - "RA4102: Report incident to external companies": ./Response_Actions/RA_4102_report_incident_to_external_companies.md
        - "RA4301: Delete malicious emails": ./Response_Actions/RA_4301_delete_malicious_emails.md
        - "RA4401: Remove file from host": ./Response_Actions/RA_4401_remove_file_from_host.md
        - "RA4701: Revoke compromised credentials": ./Response_Actions/RA_4701_revoke_compromised_credentials.md
    - Recovery:
        - "RA5101: Reinstall host from golden image": ./Response_Actions/RA_5101_reinstall_host_from_golden_image.md
    - Lessons learned:
        - "RA6101: Develop incident report": ./Response_Actions/RA_6101_develop_incident_report.md
        - "RA6102: Conduct lessons learned exercise": ./Response_Actions/RA_6102_conduct_lessons_learned_exercise.md
- Response Playbooks:
    - "RP0001: Phishing email": ./Response_Playbooks/RP_0001_phishing_email.md