site_name: RE&CT
site_dir: site/
docs_dir: docs/

theme:
    name: null
    custom_dir: 'docs/readthedocs/'
    navigation_depth: 5
    titles_only: false

repo_url: https://github.com/atc-project/atc-react
edit_uri: blob/master/docs/

plugins:
    - awesome-pages

nav:
    - Introduction:
        - RE&CT Framework: index.md
        - Response Stages: responsestages.md
    - Response Actions:
        - Preparation:
            - "RA1001: Practice": ./Response_Actions/RA_1001_practice.md
            - "RA1002: Take trainings": ./Response_Actions/RA_1002_take_trainings.md
            - "RA1003: Raise personnel awareness": ./Response_Actions/RA_1003_raise_personnel_awareness.md
            - "RA1004: Make personnel report suspicious activity": ./Response_Actions/RA_1004_make_personnel_report_suspicious_activity.md
            - "RA1005: Set up relevant data collection": ./Response_Actions/RA_1005_set_up_relevant_data_collection.md
            - "RA1006: Set up a centralized long-term log storage": ./Response_Actions/RA_1006_set_up_a_centralized_long-term_log_storage.md
            - "RA1007: Develop communication map": ./Response_Actions/RA_1007_develop_communication_map.md
            - "RA1008: Make sure there are backups": ./Response_Actions/RA_1008_make_sure_there_are_backups.md
            - "RA1009: Get network architecture map": ./Response_Actions/RA_1009_get_network_architecture_map.md
            - "RA1010: Get access control matrix": ./Response_Actions/RA_1010_get_access_control_matrix.md
            - "RA1011: Develop assets knowledge base": ./Response_Actions/RA_1011_develop_assets_knowledge_base.md
            - "RA1012: Check analysis toolset": ./Response_Actions/RA_1012_check_analysis_toolset.md
            - "RA1013: Access vulnerability management system logs": ./Response_Actions/RA_1013_access_vulnerability_management_system_logs.md
            - "RA1101: Access external network flow logs": ./Response_Actions/RA_1101_access_external_network_flow_logs.md
            - "RA1102: Access internal network flow logs": ./Response_Actions/RA_1102_access_internal_network_flow_logs.md
            - "RA1103: Access internal HTTP logs": ./Response_Actions/RA_1103_access_internal_http_logs.md
            - "RA1104: Access external HTTP logs": ./Response_Actions/RA_1104_access_external_http_logs.md
            - "RA1105: Access internal DNS logs": ./Response_Actions/RA_1105_access_internal_dns_logs.md
            - "RA1106: Access external DNS logs": ./Response_Actions/RA_1106_access_external_dns_logs.md
            - "RA1107: Access VPN logs": ./Response_Actions/RA_1107_access_vpn_logs.md
            - "RA1108: Access DHCP logs": ./Response_Actions/RA_1108_access_dhcp_logs.md
            - "RA1109: Access internal packet capture data": ./Response_Actions/RA_1109_access_internal_packet_capture_data.md
            - "RA1110: Access external packet capture data": ./Response_Actions/RA_1110_access_external_packet_capture_data.md
            - "RA1111: Get ability to block external IP address": ./Response_Actions/RA_1111_get_ability_to_block_external_ip_address.md
            - "RA1112: Get ability to block internal IP address": ./Response_Actions/RA_1112_get_ability_to_block_internal_ip_address.md
            - "RA1113: Get ability to block external domain": ./Response_Actions/RA_1113_get_ability_to_block_external_domain.md
            - "RA1114: Get ability to block internal domain": ./Response_Actions/RA_1114_get_ability_to_block_internal_domain.md
            - "RA1115: Get ability to block external URL": ./Response_Actions/RA_1115_get_ability_to_block_external_url.md
            - "RA1116: Get ability to block internal URL": ./Response_Actions/RA_1116_get_ability_to_block_internal_url.md
            - "RA1117: Get ability to block port external communication": ./Response_Actions/RA_1117_get_ability_to_block_port_external_communication.md
            - "RA1118: Get ability to block port internal communication": ./Response_Actions/RA_1118_get_ability_to_block_port_internal_communication.md
            - "RA1119: Get ability to block user external communication": ./Response_Actions/RA_1119_get_ability_to_block_user_external_communication.md
            - "RA1120: Get ability to block user internal communication": ./Response_Actions/RA_1120_get_ability_to_block_user_internal_communication.md
            - "RA1201: Get ability to list users opened email": ./Response_Actions/RA_1201_get_ability_to_list_users_opened_email.md
            - "RA1202: Get ability to list users received email": ./Response_Actions/RA_1202_get_ability_to_list_users_received_email.md
            - "RA1203: Get ability to block email domain": ./Response_Actions/RA_1203_get_ability_to_block_email_domain.md
            - "RA1204: Get ability to block email sender": ./Response_Actions/RA_1204_get_ability_to_block_email_sender.md
            - "RA1205: Get ability to delete email message": ./Response_Actions/RA_1205_get_ability_to_delete_email_message.md
            - "RA1301: Get ability to find file by format": ./Response_Actions/RA_1301_get_ability_to_find_file_by_format.md
            - "RA1302: Get ability to find file by hash": ./Response_Actions/RA_1302_get_ability_to_find_file_by_hash.md
            - "RA1303: Get ability to find file by path": ./Response_Actions/RA_1303_get_ability_to_find_file_by_path.md
            - "RA1304: Get ability to find file by content pattern": ./Response_Actions/RA_1304_get_ability_to_find_file_by_content_pattern.md
            - "RA1305: Get ability to find file by metadata": ./Response_Actions/RA_1305_get_ability_to_find_file_by_metadata.md
            - "RA1306: Get ability to find files with tampered timestamps": ./Response_Actions/RA_1306_get_ability_to_find_files_with_tampered_timestamps.md
            - "RA1307: Get ability to list files modified": ./Response_Actions/RA_1307_get_ability_to_list_files_modified.md
            - "RA1308: Get ability to list files deleted": ./Response_Actions/RA_1308_get_ability_to_list_files_deleted.md
            - "RA1309: Get ability to list files downloaded": ./Response_Actions/RA_1309_get_ability_to_list_files_downloaded.md
            - "RA1310: Get ability to download file from host": ./Response_Actions/RA_1310_get_ability_to_download_file_from_host.md
            - "RA1311: Get ability to quarantine file by format": ./Response_Actions/RA_1311_get_ability_to_quarantine_file_by_format.md
            - "RA1312: Get ability to quarantine file by hash": ./Response_Actions/RA_1312_get_ability_to_quarantine_file_by_hash.md
            - "RA1313: Get ability to quarantine file by path": ./Response_Actions/RA_1313_get_ability_to_quarantine_file_by_path.md
            - "RA1314: Get ability to quarantine file by content pattern": ./Response_Actions/RA_1314_get_ability_to_quarantine_file_by_content_pattern.md
            - "RA1315: Get ability to remove file from host": ./Response_Actions/RA_1315_get_ability_to_remove_file_from_host.md
            - "RA1501: Manage remote computer management system policies": ./Response_Actions/RA_1501_manage_remote_computer_management_system_policies.md
        - Identification:
            - "RA2001: List victims of security alert": ./Response_Actions/RA_2001_list_victims_of_security_alert.md
            - "RA2002: List host vulnerabilities": ./Response_Actions/RA_2002_list_host_vulnerabilities.md
            - "RA2003: Put compromised accounts on monitoring": ./Response_Actions/RA_2003_put_compromised_accounts_on_monitoring.md
            - "RA2101: List hosts communicated with internal domain": ./Response_Actions/RA_2101_list_hosts_communicated_with_internal_domain.md
            - "RA2102: List hosts communicated with internal IP": ./Response_Actions/RA_2102_list_hosts_communicated_with_internal_ip.md
            - "RA2103: List hosts communicated with internal URL": ./Response_Actions/RA_2103_list_hosts_communicated_with_internal_url.md
            - "RA2104: Analyse domain name": ./Response_Actions/RA_2104_analyse_domain_name.md
            - "RA2105: Analyse IP": ./Response_Actions/RA_2105_analyse_ip.md
            - "RA2106: Analyse URL": ./Response_Actions/RA_2106_analyse_uri.md
            - "RA2107: List hosts communicated by port": ./Response_Actions/RA_2107_list_hosts_communicated_by_port.md
            - "RA2108: List hosts connected to VPN": ./Response_Actions/RA_2108_list_hosts_connected_to_vpn.md
            - "RA2109: List hosts connected to intranet": ./Response_Actions/RA_2109_list_hosts_connected_to_intranet.md
            - "RA2113: List hosts communicated with external domain": ./Response_Actions/RA_2113_list_hosts_communicated_with_external_domain.md
            - "RA2114: List hosts communicated with external ip.": ./Response_Actions/RA_2114_list_hosts_communicated_with_external_ip.md
            - "RA2115: List hosts communicated with external URL": ./Response_Actions/RA_2115_list_hosts_communicated_with_external_url.md
            - "RA2201: List users opened email": ./Response_Actions/RA_2201_list_users_opened_email.md
            - "RA2202: Get original email": ./Response_Actions/RA_2202_get_original_email.md
            - "RA2203: List email receivers": ./Response_Actions/RA_2203_list_email_receivers.md
            - "RA2204: Make sure email is a phishing": ./Response_Actions/RA_2204_make_sure_email_is_a_phishing.md
            - "RA2205: Extract observables from email": ./Response_Actions/RA_2205_extract_observables_from_email.md
            - "RA2301: List files created": ./Response_Actions/RA_2301_list_files_created.md
            - "RA2302: Analyse Windows PE": ./Response_Actions/RA_2302_analyse_windows_pe.md
            - "RA2304: Analyse filehash": ./Response_Actions/RA_2304_analyse_filehash.md
            - "RA2305: Analyse macos Mach-o": ./Response_Actions/RA_2305_analyse_macos_macho.md
            - "RA2306: Analyse MS office file": ./Response_Actions/RA_2306_analyse_ms_office_file.md
            - "RA2307: Analyse PDF": ./Response_Actions/RA_2307_analyse_pdf.md
            - "RA2308: Analyse Unix ELF": ./Response_Actions/RA_2308_analyse_unix_elf.md
            - "RA2309: Find file by format": ./Response_Actions/RA_2309_find_file_by_format.md
            - "RA2310: Find file by hash": ./Response_Actions/RA_2310_find_file_by_hash.md
            - "RA2311: Find file by path": ./Response_Actions/RA_2311_find_file_by_path.md
            - "RA2312: Find file by content pattern": ./Response_Actions/RA_2312_find_file_by_content_pattern.md
            - "RA2313: Find file by metadata": ./Response_Actions/RA_2313_find_file_by_metadata.md
            - "RA2314: List files modified": ./Response_Actions/RA_2314_list_files_modified.md
            - "RA2315: List files deleted": ./Response_Actions/RA_2315_list_files_deleted.md
            - "RA2316: List files downloaded": ./Response_Actions/RA_2316_list_files_downloaded.md
            - "RA2317: List files with tampered timestamps": ./Response_Actions/RA_2317_list_files_with_tampered_timestamps.md
            - "RA2318: Download file from host": ./Response_Actions/RA_2318_download_file_from_host.md
            - "RA2401: List processes executed": ./Response_Actions/RA_2401_list_processes_executed.md
            - "RA2501: List registry keys modified": ./Response_Actions/RA_2501_list_registry_keys_modified.md
        - Containment:
            - "RA3101: Block external IP address": ./Response_Actions/RA_3101_block_external_ip_address.md
            - "RA3102: Block internal IP address": ./Response_Actions/RA_3102_block_internal_ip_address.md
            - "RA3103: Block external domain": ./Response_Actions/RA_3103_block_external_domain.md
            - "RA3104: Block internal domain": ./Response_Actions/RA_3104_block_internal_domain.md
            - "RA3105: Block external URL": ./Response_Actions/RA_3105_block_external_url.md
            - "RA3106: Block internal URL": ./Response_Actions/RA_3106_block_internal_url.md
            - "RA3107: Block port external communication": ./Response_Actions/RA_3107_block_port_external_communication.md
            - "RA3108: Block port internal communication": ./Response_Actions/RA_3108_block_port_internal_communication.md
            - "RA3109: Block user external communication": ./Response_Actions/RA_3109_block_user_external_communication.md
            - "RA3110: Block user internal communication": ./Response_Actions/RA_3110_block_user_internal_communication.md
            - "RA3201: Block domain on email": ./Response_Actions/RA_3201_block_domain_on_email.md
            - "RA3202: Block sender on email": ./Response_Actions/RA_3202_block_sender_on_email.md
            - "RA3301: Quarantine file by format": ./Response_Actions/RA_3301_quarantine_file_by_format.md
            - "RA3302: Quarantine file by hash": ./Response_Actions/RA_3302_quarantine_file_by_hash.md
            - "RA3303: Quarantine file by path": ./Response_Actions/RA_3303_quarantine_file_by_path.md
            - "RA3304: Quarantine file by content pattern": ./Response_Actions/RA_3304_quarantine_file_by_content_pattern.md
        - Eradication:
            - "RA4001: Report phishing attack to external companies": ./Response_Actions/RA_4001_report_phishing_attack_to_external_companies.md
            - "RA4002: Report incident to external companies": ./Response_Actions/RA_4002_report_incident_to_external_companies.md
            - "RA4201: Delete email message": ./Response_Actions/RA_4201_delete_email_message.md
            - "RA4301: Remove file from host": ./Response_Actions/RA_4301_remove_file_from_host.md
            - "RA4601: Revoke authentication credentials": ./Response_Actions/RA_4601_revoke_authentication_credentials.md
        - Recovery:
            - "RA5001: Reinstall host from golden image": ./Response_Actions/RA_5001_reinstall_host_from_golden_image.md
        - Lessons learned:
            - "RA6001: Develop incident report": ./Response_Actions/RA_6001_develop_incident_report.md
            - "RA6002: Conduct lessons learned exercise": ./Response_Actions/RA_6002_conduct_lessons_learned_exercise.md
    - Response Playbooks:
        - "RP0001: Phishing email": ./Response_Playbooks/RP_0001_phishing_email.md