site_name: RE&CT
site_dir: site/
docs_dir: docs/

theme:
    name: null
    custom_dir: 'docs/readthedocs/'
    navigation_depth: 4
    search_index_only: true
    titles_only: true

repo_url: https://github.com/atc-project/atc-react
edit_uri: blob/master/docs/
google_analytics: ['UA-165240552-2', 'https://atc-project.github.io/atc-react/']

plugins:
    - awesome-pages
    - exclude:
        glob:
            - "*DS_Store"
            - "*.git"
            - "*.idea"
            - "thehive_templates"
nav:
    - Introduction:
        - RE&CT Framework (EN): index.md
        - RE&CT Framework (RU): index_RU.md
        - Response Stages: responsestages.md
    - Response Actions:
        - Preparation:
            - "RA1001: Practice": ./Response_Actions/RA1001.md
            - "RA1002: Take Trainings": ./Response_Actions/RA1002.md
            - "RA1003: Raise Personnel Awareness": ./Response_Actions/RA1003.md
            - "RA1004: Make Personnel Report Suspicious Activity": ./Response_Actions/RA1004.md
            - "RA1005: Set Up Relevant Data Collection": ./Response_Actions/RA1005.md
            - "RA1006: Set Up Centralized Long-term Log Storage": ./Response_Actions/RA1006.md
            - "RA1007: Develop Communication Map": ./Response_Actions/RA1007.md
            - "RA1008: Make Sure There Are Backups": ./Response_Actions/RA1008.md
            - "RA1009: Get Network Architecture Map": ./Response_Actions/RA1009.md
            - "RA1010: Get Access Control Matrix": ./Response_Actions/RA1010.md
            - "RA1011: Develop Assets Knowledge Base": ./Response_Actions/RA1011.md
            - "RA1012: Check Analysis Toolset": ./Response_Actions/RA1012.md
            - "RA1013: Access Vulnerability Management System Logs": ./Response_Actions/RA1013.md
            - "RA1014: Connect with Trusted Communities": ./Response_Actions/RA1014.md
            - "RA1101: Access External Network Flow Logs": ./Response_Actions/RA1101.md
            - "RA1102: Access Internal Network Flow Logs": ./Response_Actions/RA1102.md
            - "RA1103: Access Internal HTTP Logs": ./Response_Actions/RA1103.md
            - "RA1104: Access External HTTP Logs": ./Response_Actions/RA1104.md
            - "RA1105: Access Internal DNS Logs": ./Response_Actions/RA1105.md
            - "RA1106: Access External DNS Logs": ./Response_Actions/RA1106.md
            - "RA1107: Access VPN Logs": ./Response_Actions/RA1107.md
            - "RA1108: Access DHCP Logs": ./Response_Actions/RA1108.md
            - "RA1109: Access Internal Packet Capture Data": ./Response_Actions/RA1109.md
            - "RA1110: Access External Packet Capture Data": ./Response_Actions/RA1110.md
            - "RA1111: Get Ability to Block External IP Address": ./Response_Actions/RA1111.md
            - "RA1112: Get Ability to Block Internal IP Address": ./Response_Actions/RA1112.md
            - "RA1113: Get Ability to Block External Domain": ./Response_Actions/RA1113.md
            - "RA1114: Get Ability to Block Internal Domain": ./Response_Actions/RA1114.md
            - "RA1115: Get Ability to Block External URL": ./Response_Actions/RA1115.md
            - "RA1116: Get Ability to Block Internal URL": ./Response_Actions/RA1116.md
            - "RA1117: Get Ability to Block Port External Communication": ./Response_Actions/RA1117.md
            - "RA1118: Get Ability to Block Port Internal Communication": ./Response_Actions/RA1118.md
            - "RA1119: Get Ability to Block User External Communication": ./Response_Actions/RA1119.md
            - "RA1120: Get Ability to Block User Internal Communication": ./Response_Actions/RA1120.md
            - "RA1121: Get Ability to Find Data Transferred by Content Pattern": ./Response_Actions/RA1121.md
            - "RA1122: Get Ability to Block Data Transferring by Content Pattern": ./Response_Actions/RA1122.md
            - "RA1123: Get Ability to List Data Transferred": ./Response_Actions/RA1123.md
            - "RA1124: Get Ability to Collect Transferred Data": ./Response_Actions/RA1124.md
            - "RA1125: Get Ability to Identify Transferred Data": ./Response_Actions/RA1125.md
            - "RA1126: Find Data Transferred by Content Pattern": ./Response_Actions/RA1126.md
            - "RA1127: Get Ability to Analyse User-agent": ./Response_Actions/RA1127.md
            - "RA1201: Get Ability to List Users Opened Email Message": ./Response_Actions/RA1201.md
            - "RA1202: Get Ability to List Email Message Receivers": ./Response_Actions/RA1202.md
            - "RA1203: Get Ability to Block Email Domain": ./Response_Actions/RA1203.md
            - "RA1204: Get Ability to Block Email Sender": ./Response_Actions/RA1204.md
            - "RA1205: Get Ability to Delete Email Message": ./Response_Actions/RA1205.md
            - "RA1206: Get Ability to Quarantine Email Message": ./Response_Actions/RA1206.md
            - "RA1207: Get Ability to Collect Email Message": ./Response_Actions/RA1207.md
            - "RA1208: Get Ability to Analyse Email Address": ./Response_Actions/RA1208.md
            - "RA1301: Get Ability to List Files Created": ./Response_Actions/RA1301.md
            - "RA1302: Get Ability to List Files Modified": ./Response_Actions/RA1302.md
            - "RA1303: Get Ability to List Files Deleted": ./Response_Actions/RA1303.md
            - "RA1304: Get Ability to List Files Downloaded": ./Response_Actions/RA1304.md
            - "RA1305: Get Ability to List Files with Tampered Timestamps": ./Response_Actions/RA1305.md
            - "RA1306: Get Ability to Find File by Path": ./Response_Actions/RA1306.md
            - "RA1307: Get Ability to Find File by Metadata": ./Response_Actions/RA1307.md
            - "RA1308: Get Ability to Find File by Hash": ./Response_Actions/RA1308.md
            - "RA1309: Get Ability to Find File by Format": ./Response_Actions/RA1309.md
            - "RA1310: Get Ability to Find File by Content Pattern": ./Response_Actions/RA1310.md
            - "RA1311: Get Ability to Collect File": ./Response_Actions/RA1311.md
            - "RA1312: Get Ability to Quarantine File by Path": ./Response_Actions/RA1312.md
            - "RA1313: Get Ability to Quarantine File by Hash": ./Response_Actions/RA1313.md
            - "RA1314: Get Ability to Quarantine File by Format": ./Response_Actions/RA1314.md
            - "RA1315: Get Ability to Quarantine File by Content Pattern": ./Response_Actions/RA1315.md
            - "RA1316: Get Ability to Remove File": ./Response_Actions/RA1316.md
            - "RA1317: Get Ability to Analyse File Hash": ./Response_Actions/RA1317.md
            - "RA1318: Get Ability to Analyse Windows PE": ./Response_Actions/RA1318.md
            - "RA1319: Get Ability to Analyse macOS Mach-O": ./Response_Actions/RA1319.md
            - "RA1320: Get Ability to Analyse Unix ELF": ./Response_Actions/RA1320.md
            - "RA1321: Get Ability to Analyse MS Office File": ./Response_Actions/RA1321.md
            - "RA1322: Get Ability to Analyse PDF File": ./Response_Actions/RA1322.md
            - "RA1323: Get Ability to Analyse Script": ./Response_Actions/RA1323.md
            - "RA1324: Get Ability to Analyse JAR": ./Response_Actions/RA1324.md
            - "RA1325: Get Ability to Analyse Filename": ./Response_Actions/RA1325.md
            - "RA1401: Get Ability to List Processes Executed": ./Response_Actions/RA1401.md
            - "RA1402: Get Ability to Find Process by Executable Path": ./Response_Actions/RA1402.md
            - "RA1403: Get Ability to Find Process by Executable Metadata": ./Response_Actions/RA1403.md
            - "RA1404: Get Ability to Find Process by Executable Hash": ./Response_Actions/RA1404.md
            - "RA1405: Get Ability to Find Process by Executable Format": ./Response_Actions/RA1405.md
            - "RA1406: Get Ability to Find Process by Executable Content Pattern": ./Response_Actions/RA1406.md
            - "RA1407: Get Ability to Block Process by Executable Path": ./Response_Actions/RA1407.md
            - "RA1408: Get Ability to Block Process by Executable Metadata": ./Response_Actions/RA1408.md
            - "RA1409: Get Ability to Block Process by Executable Hash": ./Response_Actions/RA1409.md
            - "RA1410: Get Ability to Block Process by Executable Format": ./Response_Actions/RA1410.md
            - "RA1411: Get Ability to Block Process by Executable Content Pattern": ./Response_Actions/RA1411.md
            - "RA1501: Manage Remote Computer Management System Policies": ./Response_Actions/RA1501.md
            - "RA1502: Get Ability to List Registry Keys Modified": ./Response_Actions/RA1502.md
            - "RA1503: Get Ability to List Registry Keys Deleted": ./Response_Actions/RA1503.md
            - "RA1504: Get Ability to List Registry Keys Accessed": ./Response_Actions/RA1504.md
            - "RA1505: Get Ability to List Registry Keys Created": ./Response_Actions/RA1505.md
            - "RA1506: Get Ability to List Services Created": ./Response_Actions/RA1506.md
            - "RA1507: Get Ability to List Services Modified": ./Response_Actions/RA1507.md
            - "RA1508: Get Ability to List Services Deleted": ./Response_Actions/RA1508.md
            - "RA1509: Get Ability to Remove Registry Key": ./Response_Actions/RA1509.md
            - "RA1510: Get Ability to Remove Service": ./Response_Actions/RA1510.md
            - "RA1511: Get Ability to Analyse Registry Key": ./Response_Actions/RA1511.md
            - "RA1601: Manage Identity Management System": ./Response_Actions/RA1601.md
            - "RA1602: Get Ability to Lock User Account": ./Response_Actions/RA1602.md
            - "RA1603: Get Ability to List Users Authenticated": ./Response_Actions/RA1603.md
            - "RA1604: Get Ability to Revoke Authentication Credentials": ./Response_Actions/RA1604.md
            - "RA1605: Get Ability to Remove User Account": ./Response_Actions/RA1605.md
        - Identification:
            - "RA2001: List Victims Of Security Alert": ./Response_Actions/RA2001.md
            - "RA2002: List Host Vulnerabilities": ./Response_Actions/RA2002.md
            - "RA2003: Put Compromised Accounts on Monitoring": ./Response_Actions/RA2003.md
            - "RA2101: List Hosts Communicated with Internal Domain": ./Response_Actions/RA2101.md
            - "RA2102: List Hosts Communicated with Internal IP": ./Response_Actions/RA2102.md
            - "RA2103: List Hosts Communicated with Internal URL": ./Response_Actions/RA2103.md
            - "RA2104: Analyse Domain Name": ./Response_Actions/RA2104.md
            - "RA2105: RA_2105_analyse_IP": ./Response_Actions/RA2105.md
            - "RA2106: Analyse URI": ./Response_Actions/RA2106.md
            - "RA2107: List Hosts Communicated by Port": ./Response_Actions/RA2107.md
            - "RA2108: List Hosts Connected to VPN": ./Response_Actions/RA2108.md
            - "RA2109: List Hosts Connected to Intranet": ./Response_Actions/RA2109.md
            - "RA2110: List Data Transferred": ./Response_Actions/RA2110.md
            - "RA2111: Collect Transferred Data": ./Response_Actions/RA2111.md
            - "RA2112: Identify Transferred Data": ./Response_Actions/RA2112.md
            - "RA2113: List Hosts Communicated with External Domain": ./Response_Actions/RA2113.md
            - "RA2114: List Hosts Communicated with External IP": ./Response_Actions/RA2114.md
            - "RA2115: List Hosts Communicated with External URL": ./Response_Actions/RA2115.md
            - "RA2116: Find Data Transferred by Content Pattern": ./Response_Actions/RA2116.md
            - "RA2117: Analyse User-Agent": ./Response_Actions/RA2117.md
            - "RA2201: List Users Opened Email Message": ./Response_Actions/RA2201.md
            - "RA2202: Collect Email Message": ./Response_Actions/RA2202.md
            - "RA2203: List Email Message Receivers": ./Response_Actions/RA2203.md
            - "RA2204: Make Sure Email Message is Phishing": ./Response_Actions/RA2204.md
            - "RA2205: Extract Observables from Email Message": ./Response_Actions/RA2205.md
            - "RA2206: Analyse Email Address": ./Response_Actions/RA2206.md
            - "RA2301: List Files Created": ./Response_Actions/RA2301.md
            - "RA2302: List Files Modified": ./Response_Actions/RA2302.md
            - "RA2303: List Files Deleted": ./Response_Actions/RA2303.md
            - "RA2304: List Files Downloaded": ./Response_Actions/RA2304.md
            - "RA2305: List Files with Tampered Timestamps": ./Response_Actions/RA2305.md
            - "RA2306: Find File by Path": ./Response_Actions/RA2306.md
            - "RA2307: Find File by Metadata": ./Response_Actions/RA2307.md
            - "RA2308: Find File by Hash": ./Response_Actions/RA2308.md
            - "RA2309: Find File by Format": ./Response_Actions/RA2309.md
            - "RA2310: Find File by Content Pattern": ./Response_Actions/RA2310.md
            - "RA2311: Collect File": ./Response_Actions/RA2311.md
            - "RA2312: Analyse File Hash": ./Response_Actions/RA2312.md
            - "RA2313: Analyse Windows PE": ./Response_Actions/RA2313.md
            - "RA2314: Analyse macOS Mach-O": ./Response_Actions/RA2314.md
            - "RA2315: Analyse Unix ELF": ./Response_Actions/RA2315.md
            - "RA2316: Analyse MS Office File": ./Response_Actions/RA2316.md
            - "RA2317: Analyse PDF File": ./Response_Actions/RA2317.md
            - "RA2318: Analyse Script": ./Response_Actions/RA2318.md
            - "RA2319: Analyse JAR": ./Response_Actions/RA2319.md
            - "RA2320: Analyse Filename": ./Response_Actions/RA2320.md
            - "RA2401: List Processes Executed": ./Response_Actions/RA2401.md
            - "RA2402: Find Process by Executable Path": ./Response_Actions/RA2402.md
            - "RA2403: Find Process by Executable Metadata": ./Response_Actions/RA2403.md
            - "RA2404: Find Process by Executable Hash": ./Response_Actions/RA2404.md
            - "RA2405: Find Process by Executable Format": ./Response_Actions/RA2405.md
            - "RA2406: Find Process by Executable Content Pattern": ./Response_Actions/RA2406.md
            - "RA2501: List Registry Keys Modified": ./Response_Actions/RA2501.md
            - "RA2502: List Registry Keys Deleted": ./Response_Actions/RA2502.md
            - "RA2503: List Registry Keys Accessed": ./Response_Actions/RA2503.md
            - "RA2504: List Registry Keys Created": ./Response_Actions/RA2504.md
            - "RA2505: List Services Created": ./Response_Actions/RA2505.md
            - "RA2506: List Services Modified": ./Response_Actions/RA2506.md
            - "RA2507: List Services Deleted": ./Response_Actions/RA2507.md
            - "RA2508: Analyse Registry Key": ./Response_Actions/RA2508.md
            - "RA2601: List Users Authenticated": ./Response_Actions/RA2601.md
        - Containment:
            - "RA3001: Patch Vulnerability": ./Response_Actions/RA3001.md
            - "RA3101: Block External IP Address": ./Response_Actions/RA3101.md
            - "RA3102: Block Internal IP Address": ./Response_Actions/RA3102.md
            - "RA3103: Block External Domain": ./Response_Actions/RA3103.md
            - "RA3104: Block Internal Domain": ./Response_Actions/RA3104.md
            - "RA3105: Block External URL": ./Response_Actions/RA3105.md
            - "RA3106: Block Internal URL": ./Response_Actions/RA3106.md
            - "RA3107: Block Port External Communication": ./Response_Actions/RA3107.md
            - "RA3108: Block Port Internal Communication": ./Response_Actions/RA3108.md
            - "RA3109: Block User External Communication": ./Response_Actions/RA3109.md
            - "RA3110: Block User Internal Communication": ./Response_Actions/RA3110.md
            - "RA3111: Block Data Transferring by Content Pattern": ./Response_Actions/RA3111.md
            - "RA3201: Block Domain on Email": ./Response_Actions/RA3201.md
            - "RA3202: Block Sender on Email": ./Response_Actions/RA3202.md
            - "RA3203: Quarantine Email Message": ./Response_Actions/RA3203.md
            - "RA3301: Quarantine File by Format": ./Response_Actions/RA3301.md
            - "RA3302: Quarantine File by Hash": ./Response_Actions/RA3302.md
            - "RA3303: Quarantine File by Path": ./Response_Actions/RA3303.md
            - "RA3304: Quarantine File by Content Pattern": ./Response_Actions/RA3304.md
            - "RA3401: Block Process by Executable Path": ./Response_Actions/RA3401.md
            - "RA3402: Block Process by Executable Metadata": ./Response_Actions/RA3402.md
            - "RA3403: Block Process by Executable Hash": ./Response_Actions/RA3403.md
            - "RA3404: Block Process by Executable Format": ./Response_Actions/RA3404.md
            - "RA3405: Block Process by Executable Content Pattern": ./Response_Actions/RA3405.md
            - "RA3501: Disable System Service": ./Response_Actions/RA3501.md
            - "RA3601: Lock User Account": ./Response_Actions/RA3601.md
        - Eradication:
            - "RA4001: Report Incident to External Companies": ./Response_Actions/RA4001.md
            - "RA4101: Remove Rogue Network Device": ./Response_Actions/RA4101.md
            - "RA4201: Delete Email Message": ./Response_Actions/RA4201.md
            - "RA4301: Remove File": ./Response_Actions/RA4301.md
            - "RA4501: Remove Registry Key": ./Response_Actions/RA4501.md
            - "RA4502: Remove Service": ./Response_Actions/RA4502.md
            - "RA4601: Revoke Authentication Credentials": ./Response_Actions/RA4601.md
            - "RA4602: Remove User Account": ./Response_Actions/RA4602.md
        - Recovery:
            - "RA5001: Reinstall Host from Golden Image": ./Response_Actions/RA5001.md
            - "RA5002: Restore Data from Backup": ./Response_Actions/RA5002.md
            - "RA5101: Unblock Blocked IP": ./Response_Actions/RA5101.md
            - "RA5102: Unblock Blocked Domain": ./Response_Actions/RA5102.md
            - "RA5103: Unblock Blocked URL": ./Response_Actions/RA5103.md
            - "RA5104: Unblock Blocked Port": ./Response_Actions/RA5104.md
            - "RA5105: Unblock Blocked User": ./Response_Actions/RA5105.md
            - "RA5201: Unblock Domain on Email": ./Response_Actions/RA5201.md
            - "RA5202: Unblock Sender on Email": ./Response_Actions/RA5202.md
            - "RA5203: Restore Quarantined Email Message": ./Response_Actions/RA5203.md
            - "RA5301: Restore Quarantined File": ./Response_Actions/RA5301.md
            - "RA5401: Unblock Blocked Process": ./Response_Actions/RA5401.md
            - "RA5501: Enable Disabled Service": ./Response_Actions/RA5501.md
            - "RA5601: Unlock Locked User Account": ./Response_Actions/RA5601.md
        - Lessons learned:
            - "RA6001: Develop Incident Report": ./Response_Actions/RA6001.md
            - "RA6002: Conduct Lessons Learned Exercise": ./Response_Actions/RA6002.md
    - Response Playbooks:
        - "RP0001: Phishing Email": ./Response_Playbooks/RP0001.md